CMAKE_MINIMUM_REQUIRED(VERSION 3.15)

get_filename_component(APP_FOLDER_NAME_PARENT ${CMAKE_CURRENT_LIST_DIR} NAME)

ADD_SUBDIRECTORY(ex1/)
ADD_SUBDIRECTORY(ex1Sp/)
ADD_SUBDIRECTORY(ex10/)
#ADD_SUBDIRECTORY(ex11/)
ADD_SUBDIRECTORY(ex20/)
ADD_SUBDIRECTORY(ex30/)
ADD_SUBDIRECTORY(ex31/)
ADD_SUBDIRECTORY(ex32/)
ADD_SUBDIRECTORY(ex33/)
ADD_SUBDIRECTORY(ex34/)
ADD_SUBDIRECTORY(ex35/)
ADD_SUBDIRECTORY(ex40/)


